# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DzHJ6hOZou+ZQGrsK4JJjxDEB3qVwt6OEKKJI0LOINZgb/RwJaKQcLHKofgaD6H7f1I6pRDX5lrIcANwAOpl6xERAW1RvcE1M3t8LrIoNsrz41LJAMpCjUP+EWeOCJKodQBmYl5jnQP8rDV5du6PXr8ssEzT0vCPGYrSxUJTGfyqGwP5Xz8vvEJ0yg0GRk3vm8QP5Bg4AH5i2grYm0GO2uiRRfYrxCKI4jlNbzOkqMawP2P01IGIr5l8DMM2zsQOy/AuVDWbij/E1dF/UmClSV5rTtgXq14DXTrgNaIhqMZiPIc73AJbcXG+fz9m5KbNK+Y+FpD5zqgJZbNs/a28VK9/cjmKQrXBJRrv/ZrMn/gOl5zOwKE9z/h/UOJVpVjt3/n+KPH++7VbICOBgg1KKe75+RetzQPAuBtO91UZoHzXphzck6Tn9w+I01OWbfkQRviYe10WRsh4shNZsvcRAbE2QZL65fLqRxYjPffJxHQy2/M0YJ2/9cYmnHwGpM/Z1ziJZ/lZwU974bgC6xUIaL2QBKyv9nGZcxebHQK5DqwspsnZsstghmJj18SYM2Qv6uJoRlrSm92mkC2oBiTbwKvbT6NBBIbFtBIW1dhmDeT/nB57+T5V0zZWG1B4WoaXhrk2QgN5Om4VsWfRTqBri9Zi7tGtPPdOOFjH8B1J1Gw="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
