# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CQpafTWQjP/YN6ryVT5Fsg9FuXDjgeJxJ7AoKiCabB9jfTKGKwHVCxbk5jdvivzpVbZadpRvXPWILl8FxYggAS2WeEb/PWl13abVoesMA/Mh8KRjyl9/OFoROP8L3JbMdQE6Q5NMQqXvzaamYzcKAeGHWlsD5oIbMu7VJ3ORLvhxV0zOuYGEf0xp/QrelCQvg0DWWxOeGhQsOA0grcA46DCTpHtUDashb/sJLON7mKN1c5qDi7QHXDMBBPzKMOlDzBsivdcqilcLSSUeTMj3JzFmRdbdobZ+BBHuYkXnTL8gYIncGC3fZPwT6yuCP/rWNG+pyFnqXEk0+JpzW1F+48eqaXS1Ro1z+TKIg1mE+FNfKMINKcWNviEMvEFQYA/E9ni66fl0/vTRSdReHSSxzURiKRgVp69BwPU+Ms4QuOUihRsl4Ur8jfTHA32pdWjNZ1WciBt2yiuMpu87zq92MpqrRsKi+Pb8x9vsYwpzujMBscD+v9PzDORqdXdlUMvZt8cPSRRiMwk3a+PLdDykIjbdGYd3Ppb0ySziLuwv1U6U7j1/doaQ/hne72cwUHB2IQUPWldmOlTU0aHAN9e/jzEutF2PYa4AwoGnqZ06/hvk7285Cty6I0NeaQ3JqVNSifpnAti0WtCizaZitarQnxeXVn0fYX3j3kkKuQs/86w="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
