travis:
  secure:
    BINSTAR_TOKEN: CQpafTWQjP/YN6ryVT5Fsg9FuXDjgeJxJ7AoKiCabB9jfTKGKwHVCxbk5jdvivzpVbZadpRvXPWILl8FxYggAS2WeEb/PWl13abVoesMA/Mh8KRjyl9/OFoROP8L3JbMdQE6Q5NMQqXvzaamYzcKAeGHWlsD5oIbMu7VJ3ORLvhxV0zOuYGEf0xp/QrelCQvg0DWWxOeGhQsOA0grcA46DCTpHtUDashb/sJLON7mKN1c5qDi7QHXDMBBPzKMOlDzBsivdcqilcLSSUeTMj3JzFmRdbdobZ+BBHuYkXnTL8gYIncGC3fZPwT6yuCP/rWNG+pyFnqXEk0+JpzW1F+48eqaXS1Ro1z+TKIg1mE+FNfKMINKcWNviEMvEFQYA/E9ni66fl0/vTRSdReHSSxzURiKRgVp69BwPU+Ms4QuOUihRsl4Ur8jfTHA32pdWjNZ1WciBt2yiuMpu87zq92MpqrRsKi+Pb8x9vsYwpzujMBscD+v9PzDORqdXdlUMvZt8cPSRRiMwk3a+PLdDykIjbdGYd3Ppb0ySziLuwv1U6U7j1/doaQ/hne72cwUHB2IQUPWldmOlTU0aHAN9e/jzEutF2PYa4AwoGnqZ06/hvk7285Cty6I0NeaQ3JqVNSifpnAti0WtCizaZitarQnxeXVn0fYX3j3kkKuQs/86w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
